<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tommaso Rigon">

<title>Lab 2 (Ames housing)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab2_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab2_files/libs/quarto-html/quarto.js"></script>
<script src="lab2_files/libs/quarto-html/popper.min.js"></script>
<script src="lab2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab2_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#homepage" id="toc-homepage" class="nav-link active" data-scroll-target="#homepage">Homepage</a></li>
  <li><a href="#the-ames-housing-problem" id="toc-the-ames-housing-problem" class="nav-link" data-scroll-target="#the-ames-housing-problem">The Ames housing problem</a>
  <ul class="collapse">
  <li><a href="#problem-description" id="toc-problem-description" class="nav-link" data-scroll-target="#problem-description">Problem description</a></li>
  </ul></li>
  <li><a href="#pre-processing-operations" id="toc-pre-processing-operations" class="nav-link" data-scroll-target="#pre-processing-operations">Pre-processing operations</a>
  <ul class="collapse">
  <li><a href="#a-first-look-at-the-data" id="toc-a-first-look-at-the-data" class="nav-link" data-scroll-target="#a-first-look-at-the-data">A first look at the data</a></li>
  <li><a href="#read-the-documentation" id="toc-read-the-documentation" class="nav-link" data-scroll-target="#read-the-documentation">Read the documentation</a></li>
  <li><a href="#houses-or-commercial-activities" id="toc-houses-or-commercial-activities" class="nav-link" data-scroll-target="#houses-or-commercial-activities">Houses or commercial activities?</a></li>
  <li><a href="#sales-typology" id="toc-sales-typology" class="nav-link" data-scroll-target="#sales-typology">Sales typology</a></li>
  <li><a href="#variables-and-documentation" id="toc-variables-and-documentation" class="nav-link" data-scroll-target="#variables-and-documentation">Variables and documentation</a></li>
  <li><a href="#the-output-variable" id="toc-the-output-variable" class="nav-link" data-scroll-target="#the-output-variable">The output variable</a></li>
  <li><a href="#the-output-variable-ii" id="toc-the-output-variable-ii" class="nav-link" data-scroll-target="#the-output-variable-ii">The output variable II</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">Missing values</a></li>
  <li><a href="#handling-missing-values-i" id="toc-handling-missing-values-i" class="nav-link" data-scroll-target="#handling-missing-values-i">Handling missing values I</a></li>
  <li><a href="#handling-missing-values-ii" id="toc-handling-missing-values-ii" class="nav-link" data-scroll-target="#handling-missing-values-ii">Handling missing values II</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature engineering</a></li>
  <li><a href="#deleting-irrelevant-variables" id="toc-deleting-irrelevant-variables" class="nav-link" data-scroll-target="#deleting-irrelevant-variables">Deleting irrelevant variables</a></li>
  <li><a href="#what-else" id="toc-what-else" class="nav-link" data-scroll-target="#what-else">What else?</a></li>
  <li><a href="#a-map-of-ames-iowa" id="toc-a-map-of-ames-iowa" class="nav-link" data-scroll-target="#a-map-of-ames-iowa">A map of Ames, Iowa</a></li>
  <li><a href="#training-and-test-set" id="toc-training-and-test-set" class="nav-link" data-scroll-target="#training-and-test-set">Training and test set</a></li>
  </ul></li>
  <li><a href="#predictive-modeling" id="toc-predictive-modeling" class="nav-link" data-scroll-target="#predictive-modeling">Predictive modeling</a>
  <ul class="collapse">
  <li><a href="#some-possible-predictors" id="toc-some-possible-predictors" class="nav-link" data-scroll-target="#some-possible-predictors">Some possible predictors</a></li>
  <li><a href="#graphical-analysis-dimension" id="toc-graphical-analysis-dimension" class="nav-link" data-scroll-target="#graphical-analysis-dimension">Graphical analysis (Dimension)</a></li>
  <li><a href="#graphical-analysis-quality" id="toc-graphical-analysis-quality" class="nav-link" data-scroll-target="#graphical-analysis-quality">Graphical analysis (Quality)</a></li>
  <li><a href="#graphical-analysis-other" id="toc-graphical-analysis-other" class="nav-link" data-scroll-target="#graphical-analysis-other">Graphical analysis (Other)</a></li>
  <li><a href="#the-choice-of-the-loss" id="toc-the-choice-of-the-loss" class="nav-link" data-scroll-target="#the-choice-of-the-loss">The choice of the loss</a></li>
  <li><a href="#the-worst-case-scenario" id="toc-the-worst-case-scenario" class="nav-link" data-scroll-target="#the-worst-case-scenario">The worst case scenario</a></li>
  <li><a href="#a-simple-linear-regression-i" id="toc-a-simple-linear-regression-i" class="nav-link" data-scroll-target="#a-simple-linear-regression-i">A simple linear regression I</a></li>
  <li><a href="#a-simple-linear-regression-ii" id="toc-a-simple-linear-regression-ii" class="nav-link" data-scroll-target="#a-simple-linear-regression-ii">A simple linear regression II</a></li>
  <li><a href="#a-simple-linear-regression-iii" id="toc-a-simple-linear-regression-iii" class="nav-link" data-scroll-target="#a-simple-linear-regression-iii">A simple linear regression III</a></li>
  <li><a href="#best-subset-selection" id="toc-best-subset-selection" class="nav-link" data-scroll-target="#best-subset-selection">Best subset selection</a></li>
  <li><a href="#the-full-model" id="toc-the-full-model" class="nav-link" data-scroll-target="#the-full-model">The full model</a></li>
  <li><a href="#forward-and-backward-regression" id="toc-forward-and-backward-regression" class="nav-link" data-scroll-target="#forward-and-backward-regression">Forward and backward regression</a></li>
  <li><a href="#aic-bic-and-c_p-of-mallows" id="toc-aic-bic-and-c_p-of-mallows" class="nav-link" data-scroll-target="#aic-bic-and-c_p-of-mallows">AIC, BIC and <span class="math inline">C_p</span> of Mallows</a></li>
  <li><a href="#predictions" id="toc-predictions" class="nav-link" data-scroll-target="#predictions">Predictions</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation">Cross-validation</a></li>
  <li><a href="#pcr" id="toc-pcr" class="nav-link" data-scroll-target="#pcr">PCR</a></li>
  <li><a href="#final-results" id="toc-final-results" class="nav-link" data-scroll-target="#final-results">Final results</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 2 (Ames housing)</h1>
<p class="subtitle lead">Data Mining - CdL CLAMSES</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><span class="orange">Tommaso Rigon</span> </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <em>Università degli Studi di Milano-Bicocca</em>
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<section id="homepage" class="level1">
<h1><a href="../index.html">Homepage</a></h1>
<p>This is the second lab of the course <a href="../index.html">Data Mining</a>. The code is not fully commented, because it will be executed and described in-class. The associated code <a href="../code/lab2.R">lab2.R</a> is available online.</p>
</section>
<section id="the-ames-housing-problem" class="level1">
<h1>The Ames housing problem</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/housesbanner.png" class="img-fluid figure-img"></p>
</figure>
</div>
<ul>
<li><p>Suppose you are interested in <span class="orange">buying a new house</span> in the town of Ames, which is located in the US state of Iowa.</p></li>
<li><p>You want to focus your search on houses that you expect to be able to afford.</p></li>
<li><p>Can you <span class="blue">predict</span> the price of the house based on its characteristics?</p></li>
<li><p>This is a <a href="https://www.kaggle.com/c/house-prices-advanced-regression-techniques"><strong>Kaggle</strong></a> playground competition<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. You can join the competition, if you like. Keep in mind that the full dataset, including the test set, is public…</p></li>
</ul>
<section id="problem-description" class="level2">
<h2 class="anchored" data-anchor-id="problem-description">Problem description</h2>
<ul>
<li><p>This is a prediction problem, in which the <span class="blue">sale price</span> is the <span class="orange">output</span> variable (response).</p></li>
<li><p>You have some information from all of the houses sold over the past few years, including the number of bedrooms, the size of the house, the year the house was built, etc.</p></li>
<li><p>This unit is organized into two sections:</p>
<ol type="1">
<li>We clean the data and perform some <span class="orange">exploratory data analysis</span> to gain some preliminary understanding of the data;</li>
<li>We exploit advanced regression techniques to predict the price of the house using all the remaining <span class="blue">input</span> variables (covariates).</li>
</ol></li>
<li><p>In other words, we will try to estimate a function <span class="math inline">f(\cdot)</span> such that <span class="math display">
(\texttt{SalePrice}) = f(\texttt{GarageArea},\texttt{Neighborhood}, \dots) + \epsilon.
</span></p></li>
</ul>
</section>
</section>
<section id="pre-processing-operations" class="level1">
<h1>Pre-processing operations</h1>
<section id="a-first-look-at-the-data" class="level2">
<h2 class="anchored" data-anchor-id="a-first-look-at-the-data">A first look at the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/AmesHousing.csv"</span>, )</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ames</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,930 × 82
   Order PID    `MS SubClass` `MS Zoning` `Lot Frontage` `Lot Area` Street Alley
   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;         &lt;chr&gt;                &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;
 1     1 05263… 020           RL                     141      31770 Pave   &lt;NA&gt; 
 2     2 05263… 020           RH                      80      11622 Pave   &lt;NA&gt; 
 3     3 05263… 020           RL                      81      14267 Pave   &lt;NA&gt; 
 4     4 05263… 020           RL                      93      11160 Pave   &lt;NA&gt; 
 5     5 05271… 060           RL                      74      13830 Pave   &lt;NA&gt; 
 6     6 05271… 060           RL                      78       9978 Pave   &lt;NA&gt; 
 7     7 05271… 120           RL                      41       4920 Pave   &lt;NA&gt; 
 8     8 05271… 120           RL                      43       5005 Pave   &lt;NA&gt; 
 9     9 05271… 120           RL                      39       5389 Pave   &lt;NA&gt; 
10    10 05271… 060           RL                      60       7500 Pave   &lt;NA&gt; 
# ℹ 2,920 more rows
# ℹ 74 more variables: `Lot Shape` &lt;chr&gt;, `Land Contour` &lt;chr&gt;,
#   Utilities &lt;chr&gt;, `Lot Config` &lt;chr&gt;, `Land Slope` &lt;chr&gt;,
#   Neighborhood &lt;chr&gt;, `Condition 1` &lt;chr&gt;, `Condition 2` &lt;chr&gt;,
#   `Bldg Type` &lt;chr&gt;, `House Style` &lt;chr&gt;, `Overall Qual` &lt;dbl&gt;,
#   `Overall Cond` &lt;dbl&gt;, `Year Built` &lt;dbl&gt;, `Year Remod/Add` &lt;dbl&gt;,
#   `Roof Style` &lt;chr&gt;, `Roof Matl` &lt;chr&gt;, `Exterior 1st` &lt;chr&gt;, …</code></pre>
</div>
</div>
<ul>
<li><p>The <code>ames</code> dataset has <span class="math inline">2930</span> observations (rows), each representing a different <span class="orange">building</span> in Ames, Iowa.</p></li>
<li><p>There are <span class="math inline">82</span> variables (columns), including our target: <code>SalePrice</code>.</p></li>
</ul>
</section>
<section id="read-the-documentation" class="level2">
<h2 class="anchored" data-anchor-id="read-the-documentation">Read the documentation</h2>
<ul>
<li><p>The Ames housing dataset is described in full detail here: <a href="https://jse.amstat.org/v19n3/decock.pdf" class="uri">https://jse.amstat.org/v19n3/decock.pdf</a></p></li>
<li><p>The first thing we need to do is understanding the <span class="orange">meaning of each variable</span>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(ames)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>skimr<span class="sc">::</span><span class="fu">skim</span>(ames)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>We have access to a detailed <a href="../data/ames_documentation.txt">documentation</a>. Reading the documentation can be time-consuming… but it is probably the most important part of the analysis.</li>
</ul>
</section>
<section id="houses-or-commercial-activities" class="level2">
<h2 class="anchored" data-anchor-id="houses-or-commercial-activities">Houses or commercial activities?</h2>
<ul>
<li>A minority of the observations are <span class="blue">non residential</span> buildings, as indicated by the <code>MS Zoning</code> variable.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">MS Zoning</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
A (agr) C (all)      FV I (all)      RH      RL      RM 
      2      25     139       2      27    2273     462 </code></pre>
</div>
</div>
<ul>
<li>Our goal is to predict the price of a <span class="blue">residential</span> building, therefore it makes sense to <span class="orange">exclude</span> these observations from the dataset.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># From the documentation:</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># "C (all)" = Commercial sales</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># "I (all)" = Industrial sales</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># "A (agr)" = Agricultural sales</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># "FV" = Floating village sales</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">filter</span>(ames, <span class="sc">!</span>(<span class="st">`</span><span class="at">MS Zoning</span><span class="st">`</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"C (all)"</span>, <span class="st">"I (all)"</span>, <span class="st">"A (agr)"</span>, <span class="st">"FV"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sales-typology" class="level2">
<h2 class="anchored" data-anchor-id="sales-typology">Sales typology</h2>
<ul>
<li>There is a second caveat. In the original ames dataset there are different <span class="orange">type of sales</span>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Sale Condition</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Abnorml AdjLand  Alloca  Family  Normal Partial 
    174      12      22      46    2305     203 </code></pre>
</div>
</div>
<ul>
<li><p>The prices of non-standard sales might be skewed. Moreover, we do not want to predict the price based on the type of sales (<code>Sale Type</code>).</p></li>
<li><p>We are interested only in <code>Normal</code> sales, therefore we <span class="orange">exclude</span> adjoining land purchases, deed re-allocations, internal-family sales, and incomplete houses.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Only normal sales</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">filter</span>(ames, <span class="st">`</span><span class="at">Sale Condition</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Normal"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The variables can be dropped</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">select</span>(ames, <span class="sc">-</span><span class="fu">c</span>(<span class="st">`</span><span class="at">Sale Condition</span><span class="st">`</span>, <span class="st">`</span><span class="at">Sale Type</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>After these operations, we are left with <span class="math inline">n = 2305</span> observations and <span class="math inline">80</span> variables.</li>
</ul>
</section>
<section id="variables-and-documentation" class="level2">
<h2 class="anchored" data-anchor-id="variables-and-documentation">Variables and documentation</h2>
<ul>
<li>From the documentation we learn that both <code>Order</code> and <code>PID</code> can be removed from the dataset, as they carry no information about <code>SalePrice</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the variables</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">select</span>(ames, <span class="sc">-</span><span class="fu">c</span>(Order, PID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Moreover, we can build some intuition and expectations about the variables. A few randomly selected examples:
<ul>
<li>The variable <code>Overall Qual</code> looks important, being the <em>rate of the overall material and finish of the house</em>;</li>
<li>Do we need both <code>GarageCars</code> and <code>GarageArea</code> as predictors?</li>
<li>A few variables has <span class="blue">structural missing data</span>, such as <code>FireplaceQu</code>, i.e.&nbsp;the quality of the fireplace.</li>
</ul></li>
<li><span class="blue">General tip</span>: ask yourself as many questions as possible about the data: what is the correct typology of each variable? Is it numerical, ordinal, or discrete? Are there <span class="orange">irrelevant</span> variables?)</li>
</ul>
</section>
<section id="the-output-variable" class="level2">
<h2 class="anchored" data-anchor-id="the-output-variable">The output variable</h2>
<ul>
<li><p><span class="orange">General tip</span>: start any data analysis by <span class="blue">making graphs</span> and calculating some <span class="orange">descriptive statistics</span> of the key variables.</p></li>
<li><p>The most important variable is arguably <code>SalesPrice</code>, being our target:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ames<span class="sc">$</span>SalePrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  35000  129000  157000  174640  203000  755000 </code></pre>
</div>
</div>
<ul>
<li>Thus, the average cost of a house in Ames is about 175k USD, ranging from a minimum of 35k to a maximum of 755k.</li>
</ul>
</section>
<section id="the-output-variable-ii" class="level2">
<h2 class="anchored" data-anchor-id="the-output-variable-ii">The output variable II</h2>
<ul>
<li>The distribution of <code>SalePrice</code> is slightly asymmetric, as it is often the case with prices. <span class="orange">Idea</span>: what about taking the log?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ames<span class="sc">$</span>SalePrice, <span class="at">xlab =</span> <span class="st">"Price"</span>, <span class="at">main =</span> <span class="st">"SalePrice"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(ames<span class="sc">$</span>SalePrice), <span class="at">xlab =</span> <span class="st">"Price"</span>, <span class="at">main =</span> <span class="st">"Logarithm of SalePrice"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</section>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values">Missing values</h2>
<ul>
<li>The <code>ames</code> dataset has a lot of <span class="orange">missing values</span>, most of which are <span class="blue">structural</span>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the frequency of the missing values for each variable</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>freq_missing <span class="ot">&lt;-</span> <span class="fu">apply</span>(ames, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x))) <span class="co"># Number of missing values</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(freq_missing, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>Imputation is not a good idea for most of these variables. A missing value for <code>Pool QC</code> means that there is no pool in the house, therefore we should not try to “impute” it.</p></li>
<li><p>Instead, it makes much more sense to <span class="orange">recode</span> these categorical variables.</p></li>
</ul>
</section>
<section id="handling-missing-values-i" class="level2">
<h2 class="anchored" data-anchor-id="handling-missing-values-i">Handling missing values I</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href=""><code>Alley</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href=""><code>Bsmt *</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href=""><code>Electrical</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href=""><code>Fence</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href=""><code>Fireplace Qu</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false" href=""><code>Garage *</code></a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ul>
<li>Missing values have been re-coded.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span>Alley, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Grvl Pave &lt;NA&gt; 
  99   19 2187 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span>Alley[<span class="fu">is.na</span>(ames<span class="sc">$</span>Alley)] <span class="ot">&lt;-</span> <span class="st">"No alley access"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<ul>
<li>Missing values have been re-coded.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Exposure</span><span class="st">`</span>, ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Cond</span><span class="st">`</span>, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
         Ex   Fa   Gd   Po   TA &lt;NA&gt;
  Av      1    2   15    0  282    0
  Gd      0    1   14    1  203    0
  Mn      1    8   10    0  172    0
  No      1   68   46    2 1411    0
  &lt;NA&gt;    0    0    0    0    2   65</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>id_no_bsmt <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="fu">cbind</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Exposure</span><span class="st">`</span>), <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Cond</span><span class="st">`</span>),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">BsmtFin Type 1</span><span class="st">`</span>), <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">BsmtFin Type 2</span><span class="st">`</span>),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Qual</span><span class="st">`</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>), <span class="dv">1</span>, any)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Exposure</span><span class="st">`</span>[id_no_bsmt] <span class="ot">&lt;-</span> <span class="st">"No basement"</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Cond</span><span class="st">`</span>[id_no_bsmt] <span class="ot">&lt;-</span> <span class="st">"No basement"</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">BsmtFin Type 1</span><span class="st">`</span>[id_no_bsmt] <span class="ot">&lt;-</span> <span class="st">"No basement"</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">BsmtFin Type 2</span><span class="st">`</span>[id_no_bsmt] <span class="ot">&lt;-</span> <span class="st">"No basement"</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Qual</span><span class="st">`</span>[id_no_bsmt] <span class="ot">&lt;-</span> <span class="st">"No basement"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>There are two missing values in <code>Bsmt Full Bath</code> and <code>Bsmt Half Bath</code>, which we impute with the most common value.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Full Bath</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Full Bath</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Half Bath</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Half Bath</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<ul>
<li>The missing value have been imputed with the most common observation.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span>Electrical, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FuseA FuseF FuseP SBrkr  &lt;NA&gt; 
  155    39     5  2105     1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span>Electrical[<span class="fu">is.na</span>(ames<span class="sc">$</span>Electrical)] <span class="ot">&lt;-</span> <span class="st">"SBrkr"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<ul>
<li>Missing values have been re-coded.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span>Fence, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
GdPrv  GdWo MnPrv  MnWw  &lt;NA&gt; 
  106    98   285    10  1806 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Fence</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Fence</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="st">"No fence"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<ul>
<li>Missing values have been re-coded.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Fireplace Qu</span><span class="st">`</span>, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Ex   Fa   Gd   Po   TA &lt;NA&gt; 
  27   67  530   43  535 1103 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Fireplace Qu</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Fireplace Qu</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="st">"No fireplace"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<ul>
<li>We re-code all the variables about the garage.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Cond</span><span class="st">`</span>, ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Type</span><span class="st">`</span>, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
       2Types Attchd Basment BuiltIn CarPort Detchd &lt;NA&gt;
  Ex        0      0       0       0       0      3    0
  Fa        1      4       0       0       0     56    0
  Gd        0     11       0       0       0      2    0
  Po        0      1       0       0       0      8    0
  TA       18   1350      24     136       8    570    0
  &lt;NA&gt;      0      0       0       0       0      1  112</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>id_no_garage <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="fu">cbind</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Cond</span><span class="st">`</span>), <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Finish</span><span class="st">`</span>),</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Qual</span><span class="st">`</span>), <span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Type</span><span class="st">`</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>), <span class="dv">1</span>, any)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Cond</span><span class="st">`</span>[id_no_garage] <span class="ot">&lt;-</span> <span class="st">"No garage"</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Finish</span><span class="st">`</span>[id_no_garage] <span class="ot">&lt;-</span> <span class="st">"No garage"</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Qual</span><span class="st">`</span>[id_no_garage] <span class="ot">&lt;-</span> <span class="st">"No garage"</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Garage Type</span><span class="st">`</span>[id_no_garage] <span class="ot">&lt;-</span> <span class="st">"No garage"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>The variable <code>Garage Yr Blt</code> is more problematic. By replacing missing values with <code>No garage</code> would transform this variable into a categorical variable.</p></li>
<li><p>For the sake of simplicity, given its low predictive value (i.e.&nbsp;the year of construction of the garage), in this analysis we just exclude this variable.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">select</span>(ames, <span class="sc">-</span><span class="fu">c</span>(<span class="st">`</span><span class="at">Garage Yr Blt</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="handling-missing-values-ii" class="level2">
<h2 class="anchored" data-anchor-id="handling-missing-values-ii">Handling missing values II</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href=""><code>Lot Frontage</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href=""><code>Mas Vnr *</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href=""><code>Misc Feature</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href=""><code>Pool QC</code></a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<ul>
<li><p>From the documentation: <em>Lot Frontage (Continuous): Linear feet of street connected to property</em>.</p></li>
<li><p>Even though it is not clearly specified in the documentation, it is reasonable replace missing values with <span class="math inline">0</span> (no street).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Lot Frontage</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Lot Frontage</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<ul>
<li><p>It is not clear what missing values represent: (i) an actual missing or (ii) the absence of the feature.</p></li>
<li><p>In both cases (i) and (ii) it makes sense to perform the following:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Mas Vnr Type</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Mas Vnr Type</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="st">"None"</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Mas Vnr Area</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Mas Vnr Area</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<ul>
<li>Missing values are re-coded. Tennis <code>TenC</code> is aggregated with the other categories:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Misc Feature</span><span class="st">`</span>, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Gar2 Othr Shed TenC &lt;NA&gt; 
   5    3   86    1 2210 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Misc Feature</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Misc Feature</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="st">"No additional feature"</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Misc Feature</span><span class="st">`</span>[ames<span class="sc">$</span><span class="st">`</span><span class="at">Misc Feature</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"TenC"</span>] <span class="ot">&lt;-</span> <span class="st">"Othr"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<ul>
<li>Missing values have been re-coded. All the other values have been aggregated.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Pool QC</span><span class="st">`</span>, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Ex   Fa   Gd   TA &lt;NA&gt; 
   2    2    2    3 2296 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Pool QC</span><span class="st">`</span>[<span class="fu">is.na</span>(ames<span class="sc">$</span><span class="st">`</span><span class="at">Pool QC</span><span class="st">`</span>)] <span class="ot">&lt;-</span> <span class="st">"No"</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Pool QC</span><span class="st">`</span>[ames<span class="sc">$</span><span class="st">`</span><span class="at">Pool QC</span><span class="st">`</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"TA"</span>, <span class="st">"Ex"</span>, <span class="st">"Gd"</span>, <span class="st">"Fa"</span>)] <span class="ot">&lt;-</span> <span class="st">"Yes"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering">Feature engineering</h2>
<ul>
<li><p>By “feature engineering” we mean the process of creating <span class="blue">new interesting variables</span>, possibly having a a direct relationship with the response.</p></li>
<li><p>A first example is the total dimension of the Porch, obtained as the sum of all its sub-components.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Porch Sq Feet</span><span class="st">`</span> <span class="ot">&lt;-</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Open Porch SF</span><span class="st">`</span> <span class="sc">+</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Enclosed Porch</span><span class="st">`</span> <span class="sc">+</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">3Ssn Porch</span><span class="st">`</span> <span class="sc">+</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Screen Porch</span><span class="st">`</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>In a similar spirit, we can create a variable counting the total number of bathrooms in the house.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">Tot Bathrooms</span><span class="st">`</span> <span class="ot">&lt;-</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Full Bath</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Half Bath</span><span class="st">`</span> <span class="sc">+</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Full Bath</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Bsmt Half Bath</span><span class="st">`</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Finally, we create the variable indicating the “Age” of the house.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span><span class="st">`</span><span class="at">House Age</span><span class="st">`</span> <span class="ot">&lt;-</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Yr Sold</span><span class="st">`</span> <span class="sc">-</span> ames<span class="sc">$</span><span class="st">`</span><span class="at">Year Remod/Add</span><span class="st">`</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="deleting-irrelevant-variables" class="level2">
<h2 class="anchored" data-anchor-id="deleting-irrelevant-variables">Deleting irrelevant variables</h2>
<ul>
<li><p>The theory suggests that <span class="blue">more variables</span> = <span class="orange">higher variance</span> of the estimates.</p></li>
<li><p>Thus, deleting irrelevant variables is a useful practice, as long as we expect them to be <span class="orange">not</span> related to the target variables and/or because we believe the information is already contained in other variables.</p></li>
<li><p>We already deleted <code>Order</code> and <code>PID</code> before, but other examples are the following variables:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Most of the information is already included in House Age</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">select</span>(ames, <span class="sc">-</span><span class="fu">c</span>(<span class="st">`</span><span class="at">Mo Sold</span><span class="st">`</span>, <span class="st">`</span><span class="at">Yr Sold</span><span class="st">`</span>, <span class="st">`</span><span class="at">Year Remod/Add</span><span class="st">`</span>, <span class="st">`</span><span class="at">Year Built</span><span class="st">`</span>))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Most of the information is already included in Porch Sq Feet</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">select</span>(ames, <span class="sc">-</span><span class="fu">c</span>(<span class="st">`</span><span class="at">Open Porch SF</span><span class="st">`</span>, <span class="st">`</span><span class="at">Enclosed Porch</span><span class="st">`</span>, <span class="st">`</span><span class="at">3Ssn Porch</span><span class="st">`</span>, <span class="st">`</span><span class="at">Screen Porch</span><span class="st">`</span>))</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Most of the information is already included in Tot Bathrooms</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">select</span>(ames, <span class="sc">-</span><span class="fu">c</span>(<span class="st">`</span><span class="at">Full Bath</span><span class="st">`</span>, <span class="st">`</span><span class="at">Half Bath</span><span class="st">`</span>, <span class="st">`</span><span class="at">Bsmt Full Bath</span><span class="st">`</span>, <span class="st">`</span><span class="at">Bsmt Half Bath</span><span class="st">`</span>))</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Almost no information is present in these variables</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> <span class="fu">select</span>(ames, <span class="sc">-</span><span class="fu">c</span>(<span class="st">`</span><span class="at">Pool Area</span><span class="st">`</span>, Utilities))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="what-else" class="level2">
<h2 class="anchored" data-anchor-id="what-else">What else?</h2>
<ul>
<li><p>There are certainly many other fixes one could perform on this dataset.</p></li>
<li><p>Data-cleaning is a <span class="orange">never-ending process</span>. There are certainly many other aspects of the data that improved.</p></li>
<li><p>However, we need to stop at a certain stage. In this lecture we will not perform additional data cleaning.</p></li>
<li><p>An example could be using the info contained in the variable <code>PID</code> to obtain the geographical coordinates of each house.</p></li>
<li><p>You are highly <span class="blue">encouraged</span> to <span class="orange">explore</span> / polish the data even more! It is also possible that further exploration could lead to improved predictions.</p></li>
<li><p>If you are curious about other cleaning operations that you could perform, you can have a look at this <a href="https://github.com/topepo/AmesHousing/blob/master/R/make_ames.R">R code</a> associated to this <a href="https://www.tmwr.org/ames.html">book chapter</a>.</p></li>
</ul>
</section>
<section id="a-map-of-ames-iowa" class="level2">
<h2 class="anchored" data-anchor-id="a-map-of-ames-iowa">A map of Ames, Iowa</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://www.tmwr.org/premade/ames.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">The picture has been downloaded from here: <a href="https://www.tmwr.org/ames.html" class="uri">https://www.tmwr.org/ames.html</a></figcaption>
</figure>
</div>
</section>
<section id="training-and-test-set" class="level2">
<h2 class="anchored" data-anchor-id="training-and-test-set">Training and test set</h2>
<ul>
<li><p>It is now time to split the data into <span class="blue">training set</span> (2/3 of the data) and <span class="orange">test set</span> (1/3 of the data).</p></li>
<li><p>This is very easy from a coding point of view, but it is the most delicate step: many things can go horribly wrong if this operation is not performed correctly.</p></li>
<li><p>Never perform operations involving the target variable <code>SalePrice</code> on the full dataset. In particular, never “clean” the data on the basis of the target, this could lead to overfitting.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Manual subdivision in training / test</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly allocate the id of the variables into training and test</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>id_train <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ames), <span class="at">size =</span> <span class="fu">floor</span>(<span class="dv">2</span> <span class="sc">/</span> <span class="dv">3</span> <span class="sc">*</span> <span class="fu">nrow</span>(ames)), <span class="at">replace =</span> <span class="cn">FALSE</span>))</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>id_test <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ames), id_train)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create two different datasets</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>ames_train <span class="ot">&lt;-</span> ames[id_train, ]</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>ames_test <span class="ot">&lt;-</span> ames[id_test, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>From now on, it is <span class="orange">forbidden</span> to look at the <span class="orange">test set</span> until the very end of the analysis.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="fu">data.frame</span>(ames_train), <span class="st">"../data/ames_train.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="fu">data.frame</span>(ames_test), <span class="st">"../data/ames_test.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="predictive-modeling" class="level1">
<h1>Predictive modeling</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>ames_train <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"../data/ames_train.csv"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">","</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>ames_test <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"../data/ames_train.csv"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">","</span>,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="some-possible-predictors" class="level2">
<h2 class="anchored" data-anchor-id="some-possible-predictors">Some possible predictors</h2>
<ul>
<li><p>Common sense suggest that the <span class="blue">dimension of the house</span> (i.e. <code>Gr Liv Area</code>) should be among the main predictors of the price.</p></li>
<li><p>In certain cities, such as Milan, the <code>Neighborhood</code> is highly relevant for determining the price. Do we have a similar behavior in Ames?</p></li>
<li><p>Other interesting variables are <code>Overal Qual</code>, that is the overall quality of the finitures, and <code>House Age</code>.</p></li>
<li><p>Let us have a look at these covariates to see whether they have some relationship with <code>SalePrice</code>.</p></li>
<li><p>These analyses are performed on the <span class="orange">training data</span></p></li>
</ul>
</section>
<section id="graphical-analysis-dimension" class="level2">
<h2 class="anchored" data-anchor-id="graphical-analysis-dimension">Graphical analysis (Dimension)</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">House (above ground)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Basement</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Garage</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-4" role="tab" aria-controls="tabset-3-4" aria-selected="false" href="">Porch</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-5" role="tab" aria-controls="tabset-3-5" aria-selected="false" href=""># of bathrooms</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ames_train<span class="sc">$</span>Gr.Liv.Area, ames_train<span class="sc">$</span>SalePrice,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Ground living area"</span>, <span class="at">ylab =</span> <span class="st">"Sale Price"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ames_train<span class="sc">$</span>Total.Bsmt.SF, ames_train<span class="sc">$</span>SalePrice,</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Total Basement SF"</span>, <span class="at">ylab =</span> <span class="st">"Sale Price"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ames_train<span class="sc">$</span>Garage.Area, ames_train<span class="sc">$</span>SalePrice,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Garage Area"</span>, <span class="at">ylab =</span> <span class="st">"Sale Price"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-3-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-4-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ames_train<span class="sc">$</span>Porch.Sq.Feet, ames_train<span class="sc">$</span>SalePrice,</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Porch Square Feet"</span>, <span class="at">ylab =</span> <span class="st">"Sale Price"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-3-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-5-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ames_train<span class="sc">$</span>Tot.Bathrooms, ames_train<span class="sc">$</span>SalePrice,</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Tot Bathrooms"</span>, <span class="at">ylab =</span> <span class="st">"Sale Price"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="graphical-analysis-quality" class="level2">
<h2 class="anchored" data-anchor-id="graphical-analysis-quality">Graphical analysis (Quality)</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Overall quality</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Basement quality</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false" href="">Exterior quality</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-4" role="tab" aria-controls="tabset-4-4" aria-selected="false" href="">Kitchen quality</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SalePrice <span class="sc">~</span> Overall.Qual, <span class="at">data =</span> ames_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SalePrice <span class="sc">~</span> Bsmt.Qual, <span class="at">data =</span> ames_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SalePrice <span class="sc">~</span> Exter.Qual, <span class="at">data =</span> ames_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-4-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-4-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SalePrice <span class="sc">~</span> Kitchen.Qual, <span class="at">data =</span> ames_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="graphical-analysis-other" class="level2">
<h2 class="anchored" data-anchor-id="graphical-analysis-other">Graphical analysis (Other)</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">House age</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Area</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false" href="">House category</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-4" role="tab" aria-controls="tabset-5-4" aria-selected="false" href="">Neighborhood</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ames_train<span class="sc">$</span>House.Age, ames_train<span class="sc">$</span>SalePrice,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"House Age (Years)"</span>, <span class="at">ylab =</span> <span class="st">"Sale Price"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SalePrice <span class="sc">~</span> MS.Zoning, <span class="at">data =</span> ames_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SalePrice <span class="sc">~</span> Roof.Style, <span class="at">data =</span> ames_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
</div>
<div id="tabset-5-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-4-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SalePrice <span class="sc">~</span> Neighborhood, <span class="at">data =</span> ames_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="2400"></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-choice-of-the-loss" class="level2">
<h2 class="anchored" data-anchor-id="the-choice-of-the-loss">The choice of the loss</h2>
<ul>
<li><p>We rank the performance of different models based on some notion of discrepancy between the actual values and the predictions.</p></li>
<li><p>We will use the mean absolute error (MAE) on the original scale, namely:</p></li>
</ul>
<p><span class="math display">
\text{MAE} = \frac{1}{n}\sum_{i=1}^n |\texttt{SalePrice}_i - \widehat{\texttt{SalePrice}}_i|.
</span></p>
<ul>
<li>Another possible choice is:</li>
</ul>
<p><span class="math display">
\text{RMSLE} = \sqrt{\frac{1}{n}\sum_{i=1}^n \left(\log{\{\texttt{SalePrice}_i\}} - \log{\{\widehat{\texttt{SalePrice}_i}}\}\right)^2}.
</span></p>
</section>
<section id="the-worst-case-scenario" class="level2">
<h2 class="anchored" data-anchor-id="the-worst-case-scenario">The worst case scenario</h2>
<ul>
<li>Since we want to minimize the MAE on the original scale, the median of the training set represents our baseline.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>y_hat_median <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">median</span>(ames_train<span class="sc">$</span>SalePrice), <span class="fu">nrow</span>(ames_test)) <span class="co"># Prediction</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>The following are the associated values of the loss based on the test set.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>MAE <span class="ot">&lt;-</span> <span class="cf">function</span>(y, y_fit) {</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">abs</span>(y <span class="sc">-</span> y_fit))</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>RMSLE <span class="ot">&lt;-</span> <span class="cf">function</span>(y, y_fit) {</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">mean</span>((<span class="fu">log</span>(y) <span class="sc">-</span> <span class="fu">log</span>(y_fit))<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">MAE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_median), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49625.06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">RMSLE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_median), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3727</code></pre>
</div>
</div>
<ul>
<li>Thus, any model having MAE higher that 50k and RMSLE higher than 0.37 should be regarded as a <span class="orange">coding error</span>.</li>
</ul>
</section>
<section id="a-simple-linear-regression-i" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-linear-regression-i">A simple linear regression I</h2>
<ul>
<li><p>The first model we consider is a simple linear regression, which just a few predictors that we believe are relevant for this problem.</p></li>
<li><p>We fit the following linear model</p></li>
</ul>
<p><span class="math display">
\texttt{SalePrice} = \beta_0 + \beta_1 \texttt{Gr.Liv.Area} + \cdots + \beta_4 \texttt{Tot.Bathrooms}.
</span></p>
<ul>
<li>The estimated coefficients are the following:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>m_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(SalePrice <span class="sc">~</span> Gr.Liv.Area <span class="sc">+</span> Overall.Qual <span class="sc">+</span> House.Age <span class="sc">+</span> Tot.Bathrooms, <span class="at">data =</span> ames_train)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_simple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SalePrice ~ Gr.Liv.Area + Overall.Qual + House.Age + 
    Tot.Bathrooms, data = ames_train)

Residuals:
    Min      1Q  Median      3Q     Max 
-146442  -20356   -1446   17108  264441 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -74152.556   5422.131 -13.676  &lt; 2e-16 ***
Gr.Liv.Area       50.540      2.392  21.125  &lt; 2e-16 ***
Overall.Qual   25123.430    863.489  29.095  &lt; 2e-16 ***
House.Age       -295.573     50.706  -5.829 6.78e-09 ***
Tot.Bathrooms  14320.582   1451.714   9.865  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 33430 on 1531 degrees of freedom
Multiple R-squared:  0.775, Adjusted R-squared:  0.7744 
F-statistic:  1318 on 4 and 1531 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="a-simple-linear-regression-ii" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-linear-regression-ii">A simple linear regression II</h2>
<ul>
<li>In order to assess the performance of this very simple model, we rely on the values of MAE and RMSLE based on cross-validated predictions.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>y_hat_simple <span class="ot">&lt;-</span> <span class="fu">predict</span>(m_simple, <span class="at">newdata =</span> ames_test)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a small correction:</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>y_hat_simple <span class="ot">&lt;-</span> <span class="fu">pmax</span>(y_hat_simple, <span class="dv">30000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">MAE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_simple), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23864.66</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">RMSLE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_simple), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1892</code></pre>
</div>
</div>
<ul>
<li>We also “correct” the estimates of this first linear model, so that any prediction is higher than 30k.</li>
</ul>
</section>
<section id="a-simple-linear-regression-iii" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-linear-regression-iii">A simple linear regression III</h2>
<ul>
<li><p>The proposed model is improving over the median, but we can do much better.</p></li>
<li><p>A first (very effective) idea is to rely on a multiplicative model, so that</p></li>
</ul>
<p><span class="math display">
\texttt{SalePrice} = \beta_0 \times \beta_1 \texttt{Gr Liv Area} \times \cdots \times \beta_4 \texttt{Tot Bathrooms}.
</span></p>
<ul>
<li>This is equivalent to fit a linear model on the log-scale and then transforming back the predictions, so that</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>m_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> Gr.Liv.Area <span class="sc">+</span> Overall.Qual <span class="sc">+</span> House.Age <span class="sc">+</span> Tot.Bathrooms, <span class="at">data =</span> ames_train)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_simple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(SalePrice) ~ Gr.Liv.Area + Overall.Qual + House.Age + 
    Tot.Bathrooms, data = ames_train)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.76873 -0.09598  0.00652  0.10418  0.66228 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.071e+01  2.560e-02 418.347   &lt;2e-16 ***
Gr.Liv.Area    2.471e-04  1.129e-05  21.876   &lt;2e-16 ***
Overall.Qual   1.337e-01  4.076e-03  32.792   &lt;2e-16 ***
House.Age     -2.365e-03  2.394e-04  -9.881   &lt;2e-16 ***
Tot.Bathrooms  8.481e-02  6.853e-03  12.375   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1578 on 1531 degrees of freedom
Multiple R-squared:  0.8195,    Adjusted R-squared:  0.8191 
F-statistic:  1738 on 4 and 1531 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-obtain the original scale</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>y_hat_simple <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(m_simple, <span class="at">newdata =</span> ames_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">MAE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_simple), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20577.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">RMSLE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_simple), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1576</code></pre>
</div>
</div>
</section>
<section id="best-subset-selection" class="level2">
<h2 class="anchored" data-anchor-id="best-subset-selection">Best subset selection</h2>
<ul>
<li><p>A simple linear regression model is already capable of predicting the sale price with an average error of 20k, which is remarkable given its simplicity.</p></li>
<li><p>We can improve over the previous linear model by adding more covariates…</p></li>
<li><p>However, there are too many of them! Some form of <span class="orange">regularization</span> is needed.</p></li>
</ul>
</section>
<section id="the-full-model" class="level2">
<h2 class="anchored" data-anchor-id="the-full-model">The full model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here I compute some basic quantities</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(<span class="fu">model.matrix</span>(SalePrice <span class="sc">~</span> ., <span class="at">data =</span> ames_train)[, <span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1536  223</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>m_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> ., <span class="at">data =</span> ames_train)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(SalePrice) ~ ., data = ames_train)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.62525 -0.04579  0.00114  0.04882  0.37406 

Coefficients: (9 not defined because of singularities)
                                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                        1.039e+01  2.541e-01  40.889  &lt; 2e-16 ***
MS.SubClass                       -4.367e-04  2.928e-04  -1.491 0.136120    
MS.ZoningRL                        9.869e-02  3.037e-02   3.249 0.001186 ** 
MS.ZoningRM                        4.072e-02  3.241e-02   1.256 0.209220    
Lot.Frontage                       9.326e-05  8.267e-05   1.128 0.259505    
Lot.Area                           2.790e-06  4.608e-07   6.055 1.83e-09 ***
StreetPave                        -1.435e-02  1.204e-01  -0.119 0.905166    
AlleyNo alley access               2.241e-02  1.370e-02   1.636 0.102057    
AlleyPave                          9.195e-02  2.840e-02   3.237 0.001237 ** 
Lot.ShapeIR2                       9.047e-03  1.504e-02   0.601 0.547613    
Lot.ShapeIR3                      -4.183e-02  3.486e-02  -1.200 0.230354    
Lot.ShapeReg                      -1.052e-03  6.162e-03  -0.171 0.864459    
Land.ContourHLS                    1.163e-02  1.874e-02   0.621 0.534804    
Land.ContourLow                   -9.234e-03  2.307e-02  -0.400 0.689008    
Land.ContourLvl                    1.375e-02  1.373e-02   1.001 0.317059    
Lot.ConfigCulDSac                  1.053e-02  1.178e-02   0.894 0.371384    
Lot.ConfigFR2                     -2.729e-02  1.529e-02  -1.784 0.074591 .  
Lot.ConfigFR3                     -1.722e-02  3.390e-02  -0.508 0.611562    
Lot.ConfigInside                   1.962e-03  6.605e-03   0.297 0.766537    
Land.SlopeMod                      2.263e-02  1.462e-02   1.547 0.122098    
Land.SlopeSev                     -4.726e-02  5.614e-02  -0.842 0.400081    
NeighborhoodBlueste                6.134e-02  5.540e-02   1.107 0.268443    
NeighborhoodBrDale                -6.324e-02  4.405e-02  -1.435 0.151395    
NeighborhoodBrkSide                1.754e-02  3.593e-02   0.488 0.625517    
NeighborhoodClearCr                6.305e-02  3.607e-02   1.748 0.080724 .  
NeighborhoodCollgCr                1.838e-02  3.077e-02   0.597 0.550297    
NeighborhoodCrawfor                9.239e-02  3.416e-02   2.705 0.006919 ** 
NeighborhoodEdwards               -6.685e-02  3.264e-02  -2.048 0.040760 *  
NeighborhoodGilbert                1.435e-02  3.209e-02   0.447 0.654789    
NeighborhoodGreens                 7.898e-02  4.783e-02   1.651 0.098930 .  
NeighborhoodIDOTRR                -9.432e-03  3.948e-02  -0.239 0.811215    
NeighborhoodLandmrk                3.865e-02  9.868e-02   0.392 0.695343    
NeighborhoodMeadowV               -1.344e-01  4.260e-02  -3.155 0.001641 ** 
NeighborhoodMitchel                3.806e-03  3.260e-02   0.117 0.907073    
NeighborhoodNAmes                 -2.554e-02  3.208e-02  -0.796 0.426119    
NeighborhoodNoRidge                3.544e-02  3.422e-02   1.036 0.300504    
NeighborhoodNPkVill               -3.386e-02  5.398e-02  -0.627 0.530626    
NeighborhoodNridgHt                5.077e-02  3.210e-02   1.581 0.114028    
NeighborhoodNWAmes                -1.341e-02  3.275e-02  -0.409 0.682323    
NeighborhoodOldTown               -2.743e-02  3.614e-02  -0.759 0.448045    
NeighborhoodSawyer                 6.964e-03  3.272e-02   0.213 0.831497    
NeighborhoodSawyerW               -1.966e-02  3.219e-02  -0.611 0.541594    
NeighborhoodSomerst                8.347e-02  3.889e-02   2.146 0.032045 *  
NeighborhoodStoneBr                9.306e-02  3.569e-02   2.607 0.009229 ** 
NeighborhoodSWISU                 -6.612e-02  3.692e-02  -1.791 0.073520 .  
NeighborhoodTimber                 2.992e-02  3.379e-02   0.885 0.376076    
NeighborhoodVeenker                7.113e-02  3.985e-02   1.785 0.074485 .  
Condition.1Feedr                   1.287e-02  1.751e-02   0.735 0.462493    
Condition.1Norm                    7.535e-02  1.432e-02   5.262 1.66e-07 ***
Condition.1PosA                    9.412e-02  3.081e-02   3.054 0.002300 ** 
Condition.1PosN                    7.224e-02  2.622e-02   2.755 0.005948 ** 
Condition.1RRAe                   -6.704e-03  3.048e-02  -0.220 0.825930    
Condition.1RRAn                    6.532e-02  2.593e-02   2.519 0.011887 *  
Condition.1RRNe                    4.108e-02  1.537e-01   0.267 0.789328    
Condition.1RRNn                    6.620e-02  5.422e-02   1.221 0.222383    
Condition.2Feedr                  -4.687e-02  7.999e-02  -0.586 0.557999    
Condition.2Norm                    1.006e-02  7.364e-02   0.137 0.891314    
Condition.2PosA                    5.012e-02  1.009e-01   0.497 0.619473    
Condition.2PosN                    3.508e-02  1.190e-01   0.295 0.768100    
Condition.2RRAn                   -6.659e-03  1.170e-01  -0.057 0.954618    
Condition.2RRNn                    4.409e-02  9.772e-02   0.451 0.651942    
Bldg.Type2fmCon                    3.402e-02  4.264e-02   0.798 0.425100    
Bldg.TypeDuplex                   -8.583e-03  3.117e-02  -0.275 0.783079    
Bldg.TypeTwnhs                    -3.755e-03  3.601e-02  -0.104 0.916963    
Bldg.TypeTwnhsE                    3.761e-02  3.175e-02   1.185 0.236329    
House.Style1.5Unf                 -2.232e-04  2.980e-02  -0.007 0.994025    
House.Style1Story                 -2.332e-02  1.525e-02  -1.529 0.126483    
House.Style2.5Fin                 -5.968e-02  5.301e-02  -1.126 0.260443    
House.Style2.5Unf                  4.366e-02  3.099e-02   1.409 0.159087    
House.Style2Story                  8.503e-03  1.162e-02   0.731 0.464659    
House.StyleSFoyer                  3.514e-02  2.329e-02   1.509 0.131616    
House.StyleSLvl                    2.700e-02  1.882e-02   1.435 0.151536    
Overall.Qual                       4.904e-02  3.656e-03  13.411  &lt; 2e-16 ***
Overall.Cond                       3.388e-02  2.936e-03  11.539  &lt; 2e-16 ***
Roof.StyleGable                   -5.815e-04  4.834e-02  -0.012 0.990403    
Roof.StyleGambrel                 -2.719e-02  5.715e-02  -0.476 0.634374    
Roof.StyleHip                     -6.222e-05  4.881e-02  -0.001 0.998983    
Roof.StyleMansard                 -7.749e-02  6.628e-02  -1.169 0.242506    
Roof.StyleShed                     1.396e-01  8.237e-02   1.695 0.090322 .  
Roof.MatlMembran                   1.533e-01  1.171e-01   1.309 0.190853    
Roof.MatlTar&amp;Grv                   5.604e-03  3.981e-02   0.141 0.888094    
Roof.MatlWdShake                  -2.855e-02  5.348e-02  -0.534 0.593523    
Roof.MatlWdShngl                   2.177e-02  4.379e-02   0.497 0.619221    
Exterior.1stAsphShn                6.929e-03  1.257e-01   0.055 0.956064    
Exterior.1stBrkComm                1.180e-01  8.886e-02   1.328 0.184323    
Exterior.1stBrkFace                1.178e-01  4.038e-02   2.917 0.003594 ** 
Exterior.1stCemntBd               -3.801e-02  6.109e-02  -0.622 0.533916    
Exterior.1stHdBoard                2.873e-02  3.930e-02   0.731 0.464864    
Exterior.1stImStucc                5.498e-02  1.027e-01   0.535 0.592595    
Exterior.1stMetalSd                4.680e-02  4.458e-02   1.050 0.293981    
Exterior.1stPlywood                4.124e-02  3.898e-02   1.058 0.290217    
Exterior.1stStucco                 4.020e-02  4.698e-02   0.856 0.392317    
Exterior.1stVinylSd                5.870e-04  4.309e-02   0.014 0.989134    
Exterior.1stWd Sdng                2.445e-02  3.746e-02   0.653 0.514128    
Exterior.1stWdShing                8.377e-02  4.141e-02   2.023 0.043291 *  
Exterior.2ndAsphShn                1.141e-01  7.962e-02   1.433 0.152062    
Exterior.2ndBrk Cmn                3.933e-02  6.617e-02   0.594 0.552383    
Exterior.2ndBrkFace               -7.031e-03  4.449e-02  -0.158 0.874439    
Exterior.2ndCBlock                 3.286e-01  1.163e-01   2.825 0.004807 ** 
Exterior.2ndCmentBd                1.110e-01  6.240e-02   1.778 0.075553 .  
Exterior.2ndHdBoard                4.045e-02  4.023e-02   1.006 0.314826    
Exterior.2ndImStucc                1.509e-02  5.045e-02   0.299 0.764928    
Exterior.2ndMetalSd                2.636e-02  4.549e-02   0.580 0.562347    
Exterior.2ndPlywood                2.094e-02  3.898e-02   0.537 0.591125    
Exterior.2ndStone                  1.896e-02  7.787e-02   0.244 0.807632    
Exterior.2ndStucco                -5.035e-03  4.757e-02  -0.106 0.915716    
Exterior.2ndVinylSd                8.064e-02  4.339e-02   1.859 0.063304 .  
Exterior.2ndWd Sdng                5.350e-02  3.836e-02   1.395 0.163386    
Exterior.2ndWd Shng                9.315e-03  4.059e-02   0.229 0.818529    
Mas.Vnr.TypeBrkFace                2.129e-02  2.484e-02   0.857 0.391497    
Mas.Vnr.TypeNone                   1.549e-02  2.480e-02   0.624 0.532434    
Mas.Vnr.TypeStone                  2.905e-02  2.651e-02   1.096 0.273244    
Mas.Vnr.Area                       4.368e-05  2.344e-05   1.863 0.062649 .  
Exter.QualFa                      -7.059e-02  3.889e-02  -1.815 0.069716 .  
Exter.QualGd                      -5.588e-02  2.257e-02  -2.476 0.013416 *  
Exter.QualTA                      -6.284e-02  2.441e-02  -2.574 0.010159 *  
Exter.CondFa                       2.823e-02  4.552e-02   0.620 0.535313    
Exter.CondGd                       3.134e-02  4.115e-02   0.762 0.446396    
Exter.CondPo                      -3.904e-02  7.940e-02  -0.492 0.623006    
Exter.CondTA                       4.460e-02  4.116e-02   1.084 0.278731    
FoundationCBlock                   4.142e-02  1.024e-02   4.043 5.57e-05 ***
FoundationPConc                    5.681e-02  1.109e-02   5.121 3.49e-07 ***
FoundationSlab                     6.675e-04  3.082e-02   0.022 0.982728    
FoundationStone                    1.207e-01  4.313e-02   2.799 0.005195 ** 
FoundationWood                    -2.804e-02  4.735e-02  -0.592 0.553825    
Bsmt.QualFa                       -7.998e-02  2.104e-02  -3.801 0.000151 ***
Bsmt.QualGd                       -2.790e-02  1.270e-02  -2.196 0.028231 *  
Bsmt.QualNo basement              -3.400e-02  6.751e-02  -0.504 0.614651    
Bsmt.QualTA                       -4.320e-02  1.525e-02  -2.833 0.004680 ** 
Bsmt.CondFa                        5.413e-02  5.634e-02   0.961 0.336791    
Bsmt.CondGd                        6.292e-02  5.561e-02   1.132 0.258009    
Bsmt.CondNo basement                      NA         NA      NA       NA    
Bsmt.CondPo                        2.013e-01  9.038e-02   2.228 0.026075 *  
Bsmt.CondTA                        4.409e-02  5.450e-02   0.809 0.418659    
Bsmt.ExposureGd                    2.845e-02  1.130e-02   2.518 0.011929 *  
Bsmt.ExposureMn                   -1.964e-02  1.108e-02  -1.773 0.076502 .  
Bsmt.ExposureNo                   -3.550e-03  8.614e-03  -0.412 0.680302    
Bsmt.ExposureNo basement                  NA         NA      NA       NA    
BsmtFin.Type.1BLQ                 -1.519e-03  9.889e-03  -0.154 0.877974    
BsmtFin.Type.1GLQ                  6.644e-03  8.762e-03   0.758 0.448400    
BsmtFin.Type.1LwQ                 -3.118e-02  1.245e-02  -2.506 0.012345 *  
BsmtFin.Type.1No basement                 NA         NA      NA       NA    
BsmtFin.Type.1Rec                 -1.841e-02  1.023e-02  -1.800 0.072096 .  
BsmtFin.Type.1Unf                 -2.211e-02  1.018e-02  -2.172 0.030041 *  
BsmtFin.SF.1                       1.476e-04  1.550e-05   9.522  &lt; 2e-16 ***
BsmtFin.Type.2BLQ                 -3.700e-02  2.277e-02  -1.625 0.104381    
BsmtFin.Type.2GLQ                  1.633e-02  2.731e-02   0.598 0.549912    
BsmtFin.Type.2LwQ                 -1.744e-02  2.237e-02  -0.780 0.435734    
BsmtFin.Type.2No basement                 NA         NA      NA       NA    
BsmtFin.Type.2Rec                 -2.483e-02  2.087e-02  -1.190 0.234297    
BsmtFin.Type.2Unf                 -2.118e-02  2.193e-02  -0.966 0.334343    
BsmtFin.SF.2                       1.029e-04  2.725e-05   3.777 0.000166 ***
Bsmt.Unf.SF                        9.087e-05  1.394e-05   6.518 1.01e-10 ***
Total.Bsmt.SF                             NA         NA      NA       NA    
HeatingGasA                        1.014e-01  9.448e-02   1.073 0.283450    
HeatingGasW                        1.308e-01  9.775e-02   1.338 0.181039    
HeatingGrav                        3.300e-02  1.110e-01   0.297 0.766303    
HeatingOthW                       -3.222e-04  1.173e-01  -0.003 0.997810    
HeatingWall                        1.582e-01  1.135e-01   1.394 0.163514    
Heating.QCFa                      -5.135e-02  1.573e-02  -3.265 0.001121 ** 
Heating.QCGd                      -1.712e-02  7.163e-03  -2.390 0.016979 *  
Heating.QCPo                      -1.343e-01  1.003e-01  -1.340 0.180566    
Heating.QCTA                      -3.018e-02  7.017e-03  -4.301 1.82e-05 ***
Central.AirY                       3.001e-02  1.315e-02   2.282 0.022661 *  
ElectricalFuseF                   -8.444e-03  2.245e-02  -0.376 0.706913    
ElectricalFuseP                    1.809e-03  6.628e-02   0.027 0.978234    
ElectricalSBrkr                    2.236e-03  9.996e-03   0.224 0.822994    
X1st.Flr.SF                        2.640e-04  1.665e-05  15.852  &lt; 2e-16 ***
X2nd.Flr.SF                        2.348e-04  2.024e-05  11.599  &lt; 2e-16 ***
Low.Qual.Fin.SF                    1.098e-04  5.311e-05   2.067 0.038891 *  
Gr.Liv.Area                               NA         NA      NA       NA    
Bedroom.AbvGr                      1.636e-03  4.887e-03   0.335 0.737853    
Kitchen.AbvGr                     -4.457e-02  2.544e-02  -1.752 0.080000 .  
Kitchen.QualFa                    -7.397e-02  2.265e-02  -3.267 0.001117 ** 
Kitchen.QualGd                    -4.086e-02  1.464e-02  -2.790 0.005346 ** 
Kitchen.QualPo                     3.105e-02  9.614e-02   0.323 0.746807    
Kitchen.QualTA                    -5.076e-02  1.591e-02  -3.190 0.001455 ** 
TotRms.AbvGrd                      1.594e-03  3.529e-03   0.452 0.651596    
FunctionalMaj2                    -2.902e-02  4.946e-02  -0.587 0.557519    
FunctionalMin1                     8.969e-02  3.143e-02   2.853 0.004392 ** 
FunctionalMin2                     9.076e-02  3.124e-02   2.905 0.003729 ** 
FunctionalMod                      8.596e-02  3.573e-02   2.406 0.016255 *  
FunctionalTyp                      1.304e-01  2.807e-02   4.647 3.70e-06 ***
Fireplaces                         3.375e-03  9.492e-03   0.356 0.722216    
Fireplace.QuFa                     2.246e-02  2.509e-02   0.895 0.370925    
Fireplace.QuGd                     1.828e-02  2.075e-02   0.881 0.378506    
Fireplace.QuNo fireplace          -1.347e-02  2.342e-02  -0.575 0.565083    
Fireplace.QuPo                    -5.750e-03  2.687e-02  -0.214 0.830583    
Fireplace.QuTA                     1.202e-02  2.106e-02   0.571 0.568327    
Garage.TypeAttchd                  4.282e-02  2.691e-02   1.591 0.111799    
Garage.TypeBasment                 9.779e-03  3.492e-02   0.280 0.779472    
Garage.TypeBuiltIn                 5.017e-02  2.957e-02   1.697 0.089984 .  
Garage.TypeCarPort                 2.307e-02  4.404e-02   0.524 0.600531    
Garage.TypeDetchd                  3.397e-02  2.676e-02   1.269 0.204573    
Garage.TypeNo garage              -4.453e-03  9.760e-02  -0.046 0.963614    
Garage.FinishNo garage                    NA         NA      NA       NA    
Garage.FinishRFn                  -3.109e-03  7.404e-03  -0.420 0.674621    
Garage.FinishUnf                  -7.753e-03  8.503e-03  -0.912 0.362021    
Garage.Cars                        2.331e-02  8.759e-03   2.661 0.007877 ** 
Garage.Area                        9.672e-05  3.086e-05   3.135 0.001758 ** 
Garage.QualFa                     -1.537e-01  1.321e-01  -1.164 0.244774    
Garage.QualGd                     -1.119e-01  1.268e-01  -0.883 0.377419    
Garage.QualNo garage                      NA         NA      NA       NA    
Garage.QualTA                     -1.337e-01  1.311e-01  -1.020 0.307958    
Garage.CondFa                      9.083e-02  9.629e-02   0.943 0.345704    
Garage.CondGd                      1.267e-01  9.798e-02   1.293 0.196236    
Garage.CondNo garage                      NA         NA      NA       NA    
Garage.CondPo                      1.863e-01  1.042e-01   1.787 0.074195 .  
Garage.CondTA                      1.282e-01  9.471e-02   1.353 0.176229    
Paved.DriveP                       4.545e-02  1.755e-02   2.589 0.009722 ** 
Paved.DriveY                       4.636e-02  1.158e-02   4.005 6.55e-05 ***
Wood.Deck.SF                       3.774e-05  2.047e-05   1.844 0.065402 .  
Pool.QCYes                         5.679e-02  4.746e-02   1.197 0.231648    
FenceGdWo                         -8.261e-04  1.675e-02  -0.049 0.960679    
FenceMnPrv                         2.764e-03  1.387e-02   0.199 0.842048    
FenceMnWw                         -8.054e-03  3.856e-02  -0.209 0.834583    
FenceNo fence                      7.759e-03  1.256e-02   0.618 0.536762    
Misc.FeatureNo additional feature -3.099e-02  7.886e-02  -0.393 0.694452    
Misc.FeatureOthr                  -4.755e-02  9.078e-02  -0.524 0.600522    
Misc.FeatureShed                  -3.024e-02  7.513e-02  -0.402 0.687401    
Misc.Val                           2.029e-06  7.815e-06   0.260 0.795151    
Porch.Sq.Feet                      8.717e-05  2.620e-05   3.327 0.000902 ***
Tot.Bathrooms                      2.085e-02  5.468e-03   3.812 0.000144 ***
House.Age                         -8.950e-04  1.881e-04  -4.759 2.16e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.08554 on 1321 degrees of freedom
Multiple R-squared:  0.9543,    Adjusted R-squared:  0.9469 
F-statistic: 128.8 on 214 and 1321 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>y_hat_full <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(m_full, <span class="at">newdata =</span> ames_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4 collinearities are due to "no basement", 3 collinearities are due to "no garage"</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Moreover, note that at the basement</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">cbind</span>(</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  ames_train<span class="sc">$</span>Bsmt.Unf.SF <span class="sc">+</span> ames_train<span class="sc">$</span>BsmtFin.SF<span class="fl">.1</span> <span class="sc">+</span> ames_train<span class="sc">$</span>BsmtFin.SF<span class="fl">.2</span>,</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>  ames_train<span class="sc">$</span>Total.Bsmt.SF</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,] 1080 1080
[2,]  882  882
[3,] 2110 2110
[4,]  926  926
[5,] 1280 1280
[6,] 1595 1595</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># And that at the ground floors</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">cbind</span>(ames_train<span class="sc">$</span>X1st.Flr.SF <span class="sc">+</span> ames_train<span class="sc">$</span>X2nd.Flr.SF <span class="sc">+</span> ames_train<span class="sc">$</span>Low.Qual.Fin.SF, ames_train<span class="sc">$</span>Gr.Liv.Area))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,] 1656 1656
[2,]  896  896
[3,] 2110 2110
[4,] 1604 1604
[5,] 1280 1280
[6,] 1616 1616</code></pre>
</div>
</div>
</section>
<section id="forward-and-backward-regression" class="level2">
<h2 class="anchored" data-anchor-id="forward-and-backward-regression">Forward and backward regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>fit_forward <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> ., <span class="at">data =</span> ames_train, <span class="at">method =</span> <span class="st">"forward"</span>, </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">nbest =</span> <span class="dv">1</span>, <span class="at">nvmax =</span> <span class="dv">200</span>, <span class="at">really.big =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reordering variables and trying again:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>sum_forward <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit_forward)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>fit_backward <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> ., <span class="at">data =</span> ames_train, <span class="at">method =</span> <span class="st">"backward"</span>, </span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">nbest =</span> <span class="dv">1</span>, <span class="at">nvmax =</span> <span class="dv">200</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reordering variables and trying again:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>sum_backward <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit_backward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="aic-bic-and-c_p-of-mallows" class="level2">
<h2 class="anchored" data-anchor-id="aic-bic-and-c_p-of-mallows">AIC, BIC and <span class="math inline">C_p</span> of Mallows</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>fit_forward_summary <span class="ot">&lt;-</span> fit_forward <span class="sc">%&gt;%</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p =</span> <span class="fu">sum</span>(<span class="fu">c_across</span>(MS.SubClass<span class="sc">:</span>House.Age)), <span class="at">.keep =</span> <span class="st">"unused"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a>fit_backward_summary <span class="ot">&lt;-</span> fit_backward <span class="sc">%&gt;%</span></span>
<span id="cb97-9"><a href="#cb97-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb97-10"><a href="#cb97-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb97-11"><a href="#cb97-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p =</span> <span class="fu">sum</span>(<span class="fu">c_across</span>(MS.SubClass<span class="sc">:</span>House.Age)), <span class="at">.keep =</span> <span class="st">"unused"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb97-12"><a href="#cb97-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_forward_summary<span class="sc">$</span>p, fit_forward_summary<span class="sc">$</span>r.squared, </span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">ylab =</span> <span class="st">"R-squared"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>, </span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Forward regression"</span>)</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_forward_summary<span class="sc">$</span>p, fit_forward_summary<span class="sc">$</span>mallows_cp, </span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">ylab =</span> <span class="st">"Mallows' Cp"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>, </span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Forward regression"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="1800"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_backward_summary<span class="sc">$</span>p, fit_backward_summary<span class="sc">$</span>r.squared, </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">ylab =</span> <span class="st">"R-squared"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>, </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Backward regression"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="1800"></p>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_backward_summary<span class="sc">$</span>p, fit_backward_summary<span class="sc">$</span>mallows_cp, </span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">ylab =</span> <span class="st">"Mallows' Cp"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>, </span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Backward regression"</span>)</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">which.min</span>(fit_backward_summary<span class="sc">$</span>mallows_cp), <span class="at">lty =</span> <span class="st">"dashed"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-60-2.png" class="img-fluid" width="1800"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(fit_backward_summary<span class="sc">$</span>mallows_cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 103</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="fu">which.min</span>(fit_backward_summary<span class="sc">$</span>mallows_cp), ]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         (Intercept)          MS.SubClass          MS.ZoningRL 
                   1                    2                    3 
            Lot.Area AlleyNo alley access            AlleyPave 
                   6                    8                    9 
       Lot.ConfigFR2   NeighborhoodBrDale  NeighborhoodClearCr 
                  17                   23                   25 
 NeighborhoodCrawfor  NeighborhoodEdwards   NeighborhoodGreens 
                  27                   28                   30 
 NeighborhoodMeadowV    NeighborhoodNAmes  NeighborhoodNridgHt 
                  33                   35                   38 
  NeighborhoodNWAmes  NeighborhoodOldTown  NeighborhoodSawyerW 
                  39                   40                   42 
 NeighborhoodSomerst  NeighborhoodStoneBr    NeighborhoodSWISU 
                  43                   44                   45 
 NeighborhoodVeenker      Condition.1Norm      Condition.1PosA 
                  47                   49                   50 
     Condition.1PosN      Condition.1RRAn      Bldg.Type2fmCon 
                  51                   53                   62 
     Bldg.TypeTwnhsE    House.Style1Story    House.StyleSFoyer 
                  65                   67                   71 
     House.StyleSLvl         Overall.Qual         Overall.Cond 
                  72                   73                   74 
   Roof.StyleMansard  Exterior.1stBrkComm  Exterior.1stBrkFace 
                  78                   85                   86 
 Exterior.1stMetalSd  Exterior.1stPlywood  Exterior.1stWdShing 
                  90                   91                   95 
 Exterior.2ndAsphShn   Exterior.2ndCBlock  Exterior.2ndCmentBd 
                  96                   99                  100 
 Exterior.2ndHdBoard  Exterior.2ndVinylSd  Exterior.2ndWd Sdng 
                 101                  107                  108 
        Mas.Vnr.Area         Exter.QualFa         Exter.QualGd 
                 113                  114                  115 
        Exter.QualTA         Exter.CondTA     FoundationCBlock 
                 116                  120                  121 
     FoundationPConc      FoundationStone          Bsmt.QualFa 
                 122                  124                  126 
         Bsmt.QualGd          Bsmt.QualTA          Bsmt.CondFa 
                 127                  129                  130 
         Bsmt.CondGd          Bsmt.CondPo          Bsmt.CondTA 
                 131                  133                  134 
     Bsmt.ExposureGd      Bsmt.ExposureMn    BsmtFin.Type.1LwQ 
                 135                  136                  141 
   BsmtFin.Type.1Rec    BsmtFin.Type.1Unf         BsmtFin.SF.1 
                 143                  144                  145 
   BsmtFin.Type.2GLQ         BsmtFin.SF.2          Bsmt.Unf.SF 
                 147                  152                  153 
         HeatingGasA          HeatingGasW          HeatingWall 
                 155                  156                  159 
        Heating.QCFa         Heating.QCGd         Heating.QCPo 
                 160                  161                  162 
        Heating.QCTA         Central.AirY          X1st.Flr.SF 
                 163                  164                  168 
         X2nd.Flr.SF      Low.Qual.Fin.SF        Kitchen.AbvGr 
                 169                  170                  173 
      Kitchen.QualFa       Kitchen.QualGd       Kitchen.QualTA 
                 174                  175                  177 
      FunctionalMin1       FunctionalMin2        FunctionalMod 
                 180                  181                  182 
       FunctionalTyp       Fireplace.QuFa       Fireplace.QuGd 
                 183                  185                  186 
      Fireplace.QuTA    Garage.TypeAttchd   Garage.TypeBuiltIn 
                 189                  190                  192 
         Garage.Cars          Garage.Area        Garage.QualFa 
                 199                  200                  201 
       Garage.CondPo        Garage.CondTA         Paved.DriveP 
                 208                  209                  210 
        Paved.DriveY         Wood.Deck.SF        Porch.Sq.Feet 
                 211                  212                  222 
       Tot.Bathrooms            House.Age 
                 223                  224 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="dv">1</span>, ]) <span class="co"># Model with one covariate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Overall.Qual 
           1           73 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="dv">2</span>, ]) <span class="co"># Model with two covariates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Overall.Qual  X1st.Flr.SF 
           1           73          168 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="dv">3</span>, ]) <span class="co"># Model with three covariates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Overall.Qual  X1st.Flr.SF  X2nd.Flr.SF 
           1           73          168          169 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="dv">4</span>, ]) <span class="co"># Model with four covariates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Overall.Qual BsmtFin.SF.1  X1st.Flr.SF  X2nd.Flr.SF 
           1           73          145          168          169 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="dv">5</span>, ]) <span class="co"># Model with five covariates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Overall.Qual BsmtFin.SF.1  X1st.Flr.SF  X2nd.Flr.SF    House.Age 
           1           73          145          168          169          224 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="dv">6</span>, ]) <span class="co"># Model with six covariates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)  MS.ZoningRL Overall.Qual BsmtFin.SF.1  X1st.Flr.SF  X2nd.Flr.SF 
           1            3           73          145          168          169 
   House.Age 
         224 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(sum_backward<span class="sc">$</span>which[<span class="dv">7</span>, ]) <span class="co"># Model with seven covariates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)  MS.ZoningRL Overall.Qual BsmtFin.SF.1  X1st.Flr.SF  X2nd.Flr.SF 
           1            3           73          145          168          169 
 Garage.Area    House.Age 
         200          224 </code></pre>
</div>
</div>
</section>
<section id="predictions" class="level2">
<h2 class="anchored" data-anchor-id="predictions">Predictions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>predict.regsubsets <span class="ot">&lt;-</span> <span class="cf">function</span>(object, newdata, id, ...) {</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>  form <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(object[[<span class="st">"call"</span>]][[<span class="dv">2</span>]])</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute the design matrix</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(form, newdata)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Identify the correct beta coefficients</span></span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>  beta_hat <span class="ot">&lt;-</span> <span class="fu">coef</span>(object, <span class="at">id =</span> id) </span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>  xvars <span class="ot">&lt;-</span> <span class="fu">names</span>(beta_hat)</span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Making the predictions</span></span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a>  pred_mat <span class="ot">&lt;-</span> X[, xvars] <span class="sc">%*%</span> beta_hat</span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-13"><a href="#cb119-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Housekeeping</span></span>
<span id="cb119-14"><a href="#cb119-14" aria-hidden="true" tabindex="-1"></a>  pred <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(pred_mat)</span>
<span id="cb119-15"><a href="#cb119-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(pred) <span class="ot">&lt;-</span> <span class="fu">rownames</span>(X)</span>
<span id="cb119-16"><a href="#cb119-16" aria-hidden="true" tabindex="-1"></a>  pred</span>
<span id="cb119-17"><a href="#cb119-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">exp</span>(<span class="fu">predict</span>(fit_backward, <span class="at">newdata =</span> ames_train, <span class="at">id =</span> <span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
163484.3 130584.7 204672.7 163484.3 256238.1 256238.1 </code></pre>
</div>
</div>
</section>
<section id="cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="cross-validation">Cross-validation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>p_max <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a>V <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># Number of CV fold</span></span>
<span id="cb122-7"><a href="#cb122-7" aria-hidden="true" tabindex="-1"></a>cv_fold <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(ames_train, <span class="at">v =</span> V)</span>
<span id="cb122-8"><a href="#cb122-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-9"><a href="#cb122-9" aria-hidden="true" tabindex="-1"></a>resid_back <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(ames_train), p_max <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb122-10"><a href="#cb122-10" aria-hidden="true" tabindex="-1"></a>resid_log_back <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(ames_train), p_max <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb122-11"><a href="#cb122-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-12"><a href="#cb122-12" aria-hidden="true" tabindex="-1"></a>resid_simple <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">nrow</span>(ames_train))</span>
<span id="cb122-13"><a href="#cb122-13" aria-hidden="true" tabindex="-1"></a>resid_log_simple <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">nrow</span>(ames_train))</span>
<span id="cb122-14"><a href="#cb122-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-15"><a href="#cb122-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>V) {</span>
<span id="cb122-16"><a href="#cb122-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Estimation of the null model</span></span>
<span id="cb122-17"><a href="#cb122-17" aria-hidden="true" tabindex="-1"></a>  fit_cv_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="fu">analysis</span>(cv_fold<span class="sc">$</span>splits[[k]])))</span>
<span id="cb122-18"><a href="#cb122-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb122-19"><a href="#cb122-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Simple model</span></span>
<span id="cb122-20"><a href="#cb122-20" aria-hidden="true" tabindex="-1"></a>  fit_cv_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> Gr.Liv.Area <span class="sc">+</span> Overall.Qual <span class="sc">+</span> House.Age <span class="sc">+</span> Tot.Bathrooms, </span>
<span id="cb122-21"><a href="#cb122-21" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> <span class="fu">analysis</span>(cv_fold<span class="sc">$</span>splits[[k]]))</span>
<span id="cb122-22"><a href="#cb122-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb122-23"><a href="#cb122-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Forward and backward regression</span></span>
<span id="cb122-24"><a href="#cb122-24" aria-hidden="true" tabindex="-1"></a>  fit_cv_back <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> ., <span class="at">data =</span> <span class="fu">analysis</span>(cv_fold<span class="sc">$</span>splits[[k]]), </span>
<span id="cb122-25"><a href="#cb122-25" aria-hidden="true" tabindex="-1"></a>                             <span class="at">method =</span> <span class="st">"backward"</span>, <span class="at">nbest =</span> <span class="dv">1</span>, <span class="at">nvmax =</span> p_max)</span>
<span id="cb122-26"><a href="#cb122-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-27"><a href="#cb122-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Hold-out quantities</span></span>
<span id="cb122-28"><a href="#cb122-28" aria-hidden="true" tabindex="-1"></a>  y_k <span class="ot">&lt;-</span> <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]])<span class="sc">$</span>SalePrice</span>
<span id="cb122-29"><a href="#cb122-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-30"><a href="#cb122-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Residuals for the null model</span></span>
<span id="cb122-31"><a href="#cb122-31" aria-hidden="true" tabindex="-1"></a>  y_k_null <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(fit_cv_null, <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]])))</span>
<span id="cb122-32"><a href="#cb122-32" aria-hidden="true" tabindex="-1"></a>  resid_back[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), <span class="dv">1</span>] <span class="ot">&lt;-</span> y_k <span class="sc">-</span> y_k_null</span>
<span id="cb122-33"><a href="#cb122-33" aria-hidden="true" tabindex="-1"></a>  resid_log_back[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">log</span>(y_k) <span class="sc">-</span> <span class="fu">log</span>(y_k_null)</span>
<span id="cb122-34"><a href="#cb122-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb122-35"><a href="#cb122-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Residuals for the simple model</span></span>
<span id="cb122-36"><a href="#cb122-36" aria-hidden="true" tabindex="-1"></a>  y_k_simple <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(fit_cv_simple, <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]])))</span>
<span id="cb122-37"><a href="#cb122-37" aria-hidden="true" tabindex="-1"></a>  resid_simple[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]])] <span class="ot">&lt;-</span> y_k <span class="sc">-</span> y_k_simple</span>
<span id="cb122-38"><a href="#cb122-38" aria-hidden="true" tabindex="-1"></a>  resid_log_simple[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]])] <span class="ot">&lt;-</span> <span class="fu">log</span>(y_k) <span class="sc">-</span> <span class="fu">log</span>(y_k_simple)</span>
<span id="cb122-39"><a href="#cb122-39" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb122-40"><a href="#cb122-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Residuals of the best models for different values of p</span></span>
<span id="cb122-41"><a href="#cb122-41" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>(p_max <span class="sc">+</span> <span class="dv">1</span>)) {</span>
<span id="cb122-42"><a href="#cb122-42" aria-hidden="true" tabindex="-1"></a>    y_k_back <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(fit_cv_back, <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]]), j <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb122-43"><a href="#cb122-43" aria-hidden="true" tabindex="-1"></a>    resid_back[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), j] <span class="ot">&lt;-</span> y_k <span class="sc">-</span> y_k_back</span>
<span id="cb122-44"><a href="#cb122-44" aria-hidden="true" tabindex="-1"></a>    resid_log_back[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), j] <span class="ot">&lt;-</span> <span class="fu">log</span>(y_k) <span class="sc">-</span> <span class="fu">log</span>(y_k_back)</span>
<span id="cb122-45"><a href="#cb122-45" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb122-46"><a href="#cb122-46" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb122-47"><a href="#cb122-47" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:
Reordering variables and trying again:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Housekeeping</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(y_k, y_k_back, y_k_null, y_k_simple, fit_cv_null, fit_cv_simple, fit_cv_back, j, k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>data_cv <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="dv">0</span><span class="sc">:</span>p_max,</span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">MAE =</span> <span class="fu">apply</span>(resid_back, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">mean</span>(<span class="fu">abs</span>(x))),</span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">MSLE =</span> <span class="fu">apply</span>(resid_log_back<span class="sc">^</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">mean</span>(x)),</span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE =</span> <span class="fu">apply</span>(resid_log_back<span class="sc">^</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(ames_train)))</span>
<span id="cb125-6"><a href="#cb125-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb125-7"><a href="#cb125-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-8"><a href="#cb125-8" aria-hidden="true" tabindex="-1"></a>se_rule <span class="ot">&lt;-</span> data_cv<span class="sc">$</span>MSLE[<span class="fu">which.min</span>(data_cv<span class="sc">$</span>MSLE)] <span class="sc">+</span> data_cv<span class="sc">$</span>SE[<span class="fu">which.min</span>(data_cv<span class="sc">$</span>MSLE)]</span>
<span id="cb125-9"><a href="#cb125-9" aria-hidden="true" tabindex="-1"></a>p_optimal <span class="ot">&lt;-</span> <span class="fu">which</span>(data_cv<span class="sc">$</span>MSLE <span class="sc">&lt;</span> se_rule)[<span class="dv">1</span>]</span>
<span id="cb125-10"><a href="#cb125-10" aria-hidden="true" tabindex="-1"></a>p_optimal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 168</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_cv<span class="sc">$</span>p, data_cv<span class="sc">$</span>MAE, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">ylab =</span> <span class="st">"MAE"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>)</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> p_optimal, <span class="at">lty =</span> <span class="st">'dashed'</span>)</span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(resid_simple)), <span class="at">lty =</span> <span class="st">"dotted"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid" width="1800"></p>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_cv<span class="sc">$</span>p, <span class="fu">sqrt</span>(data_cv<span class="sc">$</span>MSLE), <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.4</span>, <span class="at">ylab =</span> <span class="st">"RMSLE"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>)</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> p_optimal, <span class="at">lty =</span> <span class="st">'dashed'</span>)</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(resid_log_simple<span class="sc">^</span><span class="dv">2</span>)), <span class="at">lty =</span> <span class="st">"dotted"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-67-2.png" class="img-fluid" width="1800"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>y_hat_back <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(fit_backward, <span class="at">newdata =</span> ames_test, <span class="at">id =</span> p_optimal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pcr" class="level2">
<h2 class="anchored" data-anchor-id="pcr">PCR</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pls)</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>p_max <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>V <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>resid_pcr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(ames_train), p_max)</span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a>resid_log_pcr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(ames_train), p_max)</span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>V) {</span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb130-9"><a href="#cb130-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Estimation of the null model</span></span>
<span id="cb130-10"><a href="#cb130-10" aria-hidden="true" tabindex="-1"></a>  fit_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="fu">analysis</span>(cv_fold<span class="sc">$</span>splits[[k]])))</span>
<span id="cb130-11"><a href="#cb130-11" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb130-12"><a href="#cb130-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Hold-out dataset</span></span>
<span id="cb130-13"><a href="#cb130-13" aria-hidden="true" tabindex="-1"></a>  y_k <span class="ot">&lt;-</span> <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]])<span class="sc">$</span>SalePrice</span>
<span id="cb130-14"><a href="#cb130-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># MSE of the null model</span></span>
<span id="cb130-15"><a href="#cb130-15" aria-hidden="true" tabindex="-1"></a>  resid_pcr[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), <span class="dv">1</span>] <span class="ot">&lt;-</span> y_k <span class="sc">-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(fit_null, <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]])))</span>
<span id="cb130-16"><a href="#cb130-16" aria-hidden="true" tabindex="-1"></a>  resid_log_pcr[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">log</span>(y_k) <span class="sc">-</span> <span class="fu">predict</span>(fit_null, <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]]))</span>
<span id="cb130-17"><a href="#cb130-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb130-18"><a href="#cb130-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fitting PCR (all the components at once)</span></span>
<span id="cb130-19"><a href="#cb130-19" aria-hidden="true" tabindex="-1"></a>  fit_cv_pcr <span class="ot">&lt;-</span> <span class="fu">pcr</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> ., <span class="at">data =</span> <span class="fu">analysis</span>(cv_fold<span class="sc">$</span>splits[[k]]), <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb130-20"><a href="#cb130-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Predictions</span></span>
<span id="cb130-21"><a href="#cb130-21" aria-hidden="true" tabindex="-1"></a>  y_k_pcr <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(fit_cv_pcr, <span class="at">newdata =</span> <span class="fu">assessment</span>(cv_fold<span class="sc">$</span>splits[[k]])))</span>
<span id="cb130-22"><a href="#cb130-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>p_max) {</span>
<span id="cb130-23"><a href="#cb130-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># MSE of the best models for different values of p</span></span>
<span id="cb130-24"><a href="#cb130-24" aria-hidden="true" tabindex="-1"></a>    resid_pcr[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), j] <span class="ot">&lt;-</span> y_k <span class="sc">-</span> y_k_pcr[, , j <span class="sc">-</span> <span class="dv">1</span>]</span>
<span id="cb130-25"><a href="#cb130-25" aria-hidden="true" tabindex="-1"></a>    resid_log_pcr[<span class="fu">complement</span>(cv_fold<span class="sc">$</span>splits[[k]]), j] <span class="ot">&lt;-</span> <span class="fu">log</span>(y_k) <span class="sc">-</span> <span class="fu">log</span>(y_k_pcr[, , j <span class="sc">-</span> <span class="dv">1</span>])</span>
<span id="cb130-26"><a href="#cb130-26" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb130-27"><a href="#cb130-27" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>data_cv <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="dv">1</span><span class="sc">:</span>p_max,</span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">MAE =</span> <span class="fu">apply</span>(resid_pcr, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">mean</span>(<span class="fu">abs</span>(x))),</span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">MSLE =</span> <span class="fu">apply</span>(resid_log_pcr<span class="sc">^</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">mean</span>(x)),</span>
<span id="cb131-5"><a href="#cb131-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE =</span> <span class="fu">apply</span>(resid_log_pcr<span class="sc">^</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(ames_train)))</span>
<span id="cb131-6"><a href="#cb131-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb131-7"><a href="#cb131-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-8"><a href="#cb131-8" aria-hidden="true" tabindex="-1"></a>se_rule <span class="ot">&lt;-</span> data_cv<span class="sc">$</span>MSLE[<span class="fu">which.min</span>(data_cv<span class="sc">$</span>MSLE)] <span class="sc">+</span> data_cv<span class="sc">$</span>SE[<span class="fu">which.min</span>(data_cv<span class="sc">$</span>MSLE)]</span>
<span id="cb131-9"><a href="#cb131-9" aria-hidden="true" tabindex="-1"></a>p_optimal <span class="ot">&lt;-</span> <span class="fu">which</span>(data_cv<span class="sc">$</span>MSLE <span class="sc">&lt;</span> se_rule)[<span class="dv">1</span>]</span>
<span id="cb131-10"><a href="#cb131-10" aria-hidden="true" tabindex="-1"></a>p_optimal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 110</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_cv<span class="sc">$</span>p, data_cv<span class="sc">$</span>MAE, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">ylab =</span> <span class="st">"MAE"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>)</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> p_optimal, <span class="at">lty =</span> <span class="st">'dashed'</span>)</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(resid_simple)), <span class="at">lty =</span> <span class="st">"dotted"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid" width="1800"></p>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_cv<span class="sc">$</span>p, <span class="fu">sqrt</span>(data_cv<span class="sc">$</span>MSLE), <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">ylab =</span> <span class="st">"RMSLE"</span>, <span class="at">xlab =</span> <span class="st">"p"</span>)</span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> p_optimal, <span class="at">lty =</span> <span class="st">'dashed'</span>)</span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(resid_log_simple<span class="sc">^</span><span class="dv">2</span>)), <span class="at">lty =</span> <span class="st">"dotted"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab2_files/figure-html/unnamed-chunk-71-2.png" class="img-fluid" width="1800"></p>
</div>
</div>
</section>
<section id="final-results" class="level2">
<h2 class="anchored" data-anchor-id="final-results">Final results</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Null</span></span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">MAE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_median), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49625.06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">RMSLE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_median), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3727</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple</span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">MAE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_simple), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20577.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">RMSLE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_simple), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1576</code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full</span></span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">MAE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_full), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9866.944</code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">RMSLE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_full), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0793</code></pre>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Backward</span></span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">MAE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_back), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10897.54</code></pre>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">RMSLE</span>(ames_test<span class="sc">$</span>SalePrice, y_hat_back), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0855</code></pre>
</div>
</div>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>De Cock, D. 2011. “Ames, Iowa: Alternative to the Boston Housing Data as an End of Semester Regression Project.” Journal of Statistics Education 19 (3).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="lab2_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>